name: 'mongo-clone-action-macos'
description: 'Github action to trigger mongoDB database clones via mongodump & mongorestore on macOS'
inputs:
  source:
    description: 'MongoDB connect url that includes username, password & database name you want to clone from'
    required: true
  target:
    description: 'MongoDB connect url that includes username, password & database name you want to clone to'
    required: true

runs:
  using: "macos-latest"
  steps:
    - name: Clone Database
      run: ${{ github.action_path }}/clone.sh ${{ inputs.source }} ${{ inputs.target }}
      shell: bash

branding:
  icon: 'server'
  color: 'gray-dark'
