name: 'mongo-clone-action-macos'
description: 'Github action to trigger mongoDB database clones via mongodump & mongorestore on macOS'
inputs:
  source:
    description: 'MongoDB connect url that includes username, password & database name you want to clone from'
    required: true
  target:
    description: 'MongoDB connect url that includes username, password & database name you want to clone to'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install MongoDB step 1
      run: wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | sudo apt-key add -
      shell: bash
    - name: Install MongoDB step 2
      run: echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
      shell: bash
    - name: Install MongoDB step 3
      run: sudo apt-get update
      shell: bash
    - name: Install MongoDB step 4
      run: sudo apt-get install -y mongodb-org
      shell: bash
    - name: Clone Database
      run: ${{ github.action_path }}/clone.sh ${{ inputs.source }} ${{ inputs.target }}
      shell: bash

branding:
  icon: 'server'
  color: 'gray-dark'
